import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import axios from 'axios';
import {BrowserRouter,useNavigate} from 'react-router-dom';
import {BookOpen,LayoutDashboard,Users,ArrowLeftRight,LogOut,Plus,Search,Trash2} from 'lucide-react';
import './styles.css';

const API='http://127.0.0.1:8000/api';
const api=axios.create({baseURL:API});
api.interceptors.request.use(c=>{const t=localStorage.getItem('token'); if(t)c.headers.Authorization=`Bearer ${t}`; return c});

function Login({onLogin}){const [email,setEmail]=useState('admin@library.com'),[password,setPassword]=useState('admin123'),[err,setErr]=useState('');
const submit=async e=>{e.preventDefault();try{const r=await api.post('/auth/login/',{email,password});localStorage.setItem('token',r.data.token);localStorage.setItem('user',JSON.stringify(r.data.user));onLogin(r.data.user)}catch(e){setErr(e.response?.data?.detail||'Login failed')}};return <div className="login"><div className="login-card"><div className="logo"><BookOpen/> Smart Library</div><h1>Welcome back</h1><p>Manage your library in one place.</p>{err&&<div className="error">{err}</div>}<form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button>Sign in</button></form><small>Admin: admin@library.com / admin123<br/>Student: student@library.com / student123</small></div></div>}

function App(){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('user')||'null'));return user?<Dashboard user={user} logout={()=>{localStorage.clear();setUser(null)}}/>:<Login onLogin={setUser}/>}

function Dashboard({user,logout}){const [tab,setTab]=useState('dashboard'),[data,setData]=useState({}),[books,setBooks]=useState([]),[members,setMembers]=useState([]),[tx,setTx]=useState([]),[q,setQ]=useState(''),[showAdd,setShowAdd]=useState(false);
const load=async()=>{const [d,b,m,t]=await Promise.all([api.get('/dashboard/'),api.get('/books/'),api.get('/members/'),api.get('/transactions/')]);setData(d.data);setBooks(b.data.books);setMembers(m.data.members);setTx(t.data.transactions)};useEffect(()=>{load()},[]);
const issue=async id=>{const me=members.find(x=>x.email===user.email)||members[0];if(!me)return alert('Add a member first');try{await api.post('/transactions/issue/',{book_id:id,member_id:me.id});load()}catch(e){alert(e.response?.data?.detail||'Issue failed')}};
const ret=async id=>{const r=await api.post(`/transactions/${id}/return/`);alert(`Fine: ₹${r.data.fine}`);load()};
const del=async id=>{if(confirm('Delete this book?')){await api.delete(`/books/${id}/`);load()}};
const filtered=books.filter(b=>[b.title,b.author,b.isbn,b.category].join(' ').toLowerCase().includes(q.toLowerCase()));
return <div className="app"><aside><div className="brand"><BookOpen/> Smart Library</div><div className="nav">{[['dashboard','Dashboard',LayoutDashboard],['books','Books',BookOpen],['members','Members',Users],['transactions','Transactions',ArrowLeftRight]].map(([id,label,I])=><button className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={18}/>{label}</button>)}</div><button className="logout" onClick={logout}><LogOut size={18}/>Logout</button></aside><main><header><div><h2>{tab[0].toUpperCase()+tab.slice(1)}</h2><span>Welcome, {user.name}</span></div></header>
{tab==='dashboard'&&<><div className="stats">{[['Total Books',data.total_books],['Available',data.available_books],['Issued',data.issued_books],['Members',data.members],['Overdue',data.overdue],['Fine Collected',`₹${data.pending_fines||0}`]].map(x=><div className="stat"><span>{x[0]}</span><strong>{x[1]??0}</strong></div>)}</div><section className="panel"><h3>Quick Actions</h3><div className="actions"><button onClick={()=>setTab('books')}><BookOpen/> Manage Books</button><button onClick={()=>setTab('transactions')}><ArrowLeftRight/> View Transactions</button><button onClick={()=>setTab('members')}><Users/> View Members</button></div></section></>}
{tab==='books'&&<section className="panel"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search title, author, ISBN..." value={q} onChange={e=>setQ(e.target.value)}/></div>{user.role==='admin'&&<button onClick={()=>setShowAdd(true)}><Plus size={17}/> Add Book</button>}</div><div className="tablewrap"><table><thead><tr><th>Book</th><th>Author</th><th>Category</th><th>ISBN</th><th>Available</th><th>Action</th></tr></thead><tbody>{filtered.map(b=><tr><td><b>{b.title}</b><br/><small>{b.publisher||''} · {b.year||''}</small></td><td>{b.author}</td><td><span className="pill">{b.category}</span></td><td>{b.isbn}</td><td>{b.available_copies}/{b.total_copies}</td><td><button className="small" disabled={!b.available_copies} onClick={()=>issue(b.id)}>Issue</button>{user.role==='admin'&&<button className="icon" onClick={()=>del(b.id)}><Trash2 size={16}/></button>}</td></tr>)}</tbody></table></div></section>}
{tab==='members'&&<section className="panel"><div className="tablewrap"><table><thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Department</th><th>Year</th><th>Status</th></tr></thead><tbody>{members.map(m=><tr><td><b>{m.name}</b></td><td>{m.email}</td><td>{m.phone}</td><td>{m.department}</td><td>{m.year}</td><td><span className="pill">{m.status}</span></td></tr>)}</tbody></table></div></section>}
{tab==='transactions'&&<section className="panel"><div className="tablewrap"><table><thead><tr><th>Book</th><th>Issue Date</th><th>Due Date</th><th>Status</th><th>Fine</th><th>Action</th></tr></thead><tbody>{tx.map(t=><tr><td>{t.book_title}</td><td>{new Date(t.issue_date).toLocaleDateString()}</td><td>{new Date(t.due_date).toLocaleDateString()}</td><td><span className="pill">{t.status}</span></td><td>₹{t.fine||0}</td><td>{t.status==='Issued'&&<button className="small" onClick={()=>ret(t.id)}>Return</button>}</td></tr>)}</tbody></table></div></section>}
{showAdd&&<AddBook close={()=>setShowAdd(false)} done={load}/>}</main></div>}

function AddBook({close,done}){const [f,setF]=useState({title:'',author:'',isbn:'',category:'Programming',publisher:'',year:2026,total_copies:1,shelf:''});const ch=e=>setF({...f,[e.target.name]:e.target.value});const save=async e=>{e.preventDefault();await api.post('/books/',{...f,total_copies:Number(f.total_copies),available_copies:Number(f.total_copies),year:Number(f.year)});close();done()};return <div className="modal"><form className="modal-card" onSubmit={save}><h3>Add New Book</h3>{['title','author','isbn','category','publisher','year','total_copies','shelf'].map(k=><input required name={k} placeholder={k.replace('_',' ')} value={f[k]} onChange={ch}/>)}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button>Add Book</button></div></form></div>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
